//! Parser for `OP_MobUpdate` — payload `spawnPositionUpdate`, 18 bytes.
//!
//! The struct layout (size, field offsets, bitfield positions) comes
//! from `crate::eqstructs::spawnPositionUpdate`, generated by bindgen
//! against `scry-cpp/src/everquest.h`. Bindgen's bitfield getters
//! mask but don't sign-extend signed bitfields, so the 19-bit signed
//! position fields go through [`sign_extend`] before the daemon's
//! `>> 3` fixed-point conversion (1/8-unit → integer game world).
//! Heading is 12-bit unsigned and passed through unchanged.

use crate::eqstructs::{sign_extend, spawnPositionUpdate};
use thiserror::Error;

pub const PAYLOAD_LEN: usize = std::mem::size_of::<spawnPositionUpdate>();

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct MobUpdate {
    pub spawn_id: u16,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub heading: u16,
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum ParseError {
    #[error("expected {PAYLOAD_LEN} bytes, got {0}")]
    BadLength(usize),
}

pub fn parse_mob_update(bytes: &[u8]) -> Result<MobUpdate, ParseError> {
    if bytes.len() != PAYLOAD_LEN {
        return Err(ParseError::BadLength(bytes.len()));
    }

    // Layout lives on the struct (y bits 0..18 | z 19..37 | 7-bit gap | x
    // 45..63, ×8 fixed-point). Its accessors mask but don't sign-extend, so
    // that and the >>3 happen here. The 08/25 patch moved the block from byte
    // 4 to byte 8; the bit layout inside it is unchanged.
    //
    // X/Y corrected 2026-08-03. Upstream's spawnPositionUpdateEQL names these
    // in the wire frame and swaps x/y at the call site; the 07/28 rewrite took
    // its labels without that swap. We name fields in the map frame, so no
    // swap here. See OPCODES_LEGENDS.md.
    let raw: spawnPositionUpdate =
        unsafe { std::ptr::read_unaligned(bytes.as_ptr() as *const spawnPositionUpdate) };
    let spawn_id = unsafe { std::ptr::addr_of!(raw.spawnId).read_unaligned() } as u16;
    let coord = |v: u64| sign_extend(v as u32, 19) >> 3;
    let y = coord(raw.y());
    let z = coord(raw.z());
    let x = coord(raw.x());
    let heading = raw.heading() as u16;

    Ok(MobUpdate {
        spawn_id,
        x,
        y,
        z,
        heading,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_wrong_length() {
        assert_eq!(parse_mob_update(&[]), Err(ParseError::BadLength(0)));
        assert_eq!(parse_mob_update(&[0; 17]), Err(ParseError::BadLength(17)));
        assert_eq!(parse_mob_update(&[0; 19]), Err(ParseError::BadLength(19)));
        // the pre-08/25 size is now rejected
        assert_eq!(parse_mob_update(&[0; 14]), Err(ParseError::BadLength(14)));
    }

    #[test]
    fn all_zero_payload() {
        assert_eq!(
            parse_mob_update(&[0; 18]).unwrap(),
            MobUpdate {
                spawn_id: 0,
                x: 0,
                y: 0,
                z: 0,
                heading: 0
            },
        );
    }

    #[test]
    fn sign_extension_negative_y() {
        // y is bits 0..18 of the 64-bit packed unit at byte 8. Set it to
        // 0x4_0000 (the 19-bit signed minimum, -262144 before the >>3).
        let mut bytes = [0u8; 18];
        let bf: u64 = 0x4_0000u64;
        bytes[8..16].copy_from_slice(&bf.to_le_bytes());
        let m = parse_mob_update(&bytes).unwrap();
        assert_eq!(m.y, -32768);
        assert_eq!(m.x, 0);
        assert_eq!(m.z, 0);
    }

    // The gap before the last field is what the pre-patch binding omitted; pin
    // each coordinate at its own offset so a future regeneration cannot re-shift
    // them. Distinct values per axis so a transpose fails loudly — the 07/28
    // rewrite put x and y the wrong way round and nothing here caught it.
    // identity_op: the `<< 0` is the bit POSITION of the first field, parallel to
    // `<< 19` and `<< 45` — the asserts below cite those ranges. Folding it away
    // would hide where the pack starts.
    #[allow(clippy::identity_op)]
    #[test]
    fn each_coordinate_reads_from_its_own_field() {
        let mut bytes = [0u8; 18];
        let bf: u64 = (800u64 << 0) | (16u64 << 19) | (2400u64 << 45);
        bytes[8..16].copy_from_slice(&bf.to_le_bytes());
        let m = parse_mob_update(&bytes).unwrap();
        assert_eq!(m.y, 100); // 800 >> 3  — bits 0..18
        assert_eq!(m.z, 2); //  16 >> 3  — bits 19..37
        assert_eq!(m.x, 300); // 2400 >> 3 — bits 45..63
    }

    // A real 08/25 broadcast whose spawn also appears in OP_NpcMoveUpdate, which
    // decodes the SAME position and facing from an unrelated big-endian
    // sign-magnitude layout. Two independent streams agreeing pins the axis
    // assignment and the heading offset against wire bytes, not a synthetic pack.
    #[test]
    fn decodes_a_captured_update() {
        let bytes: [u8; PAYLOAD_LEN] = [
            0x0C, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x33, 0xF3, 0x07, 0x01, 0x00, 0xA0,
            0x6B, 0xFF, 0xC0, 0x7F,
        ];
        let m = parse_mob_update(&bytes).unwrap();
        assert_eq!(m.spawn_id, 25612);
        assert_eq!((m.x, m.y, m.z), (-149, -410, 4));
        // heading rides the HIGH 12 bits of the trailing u16, not the low ones
        assert_eq!(m.heading, 2044);
    }
}
